spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /api/users/$\{segment}

        # Asset Service
        - id: asset-service
          uri: lb://asset-service
          predicates:
            - Path=/api/assets/**
          filters:
            - RewritePath=/api/assets/(?<segment>.*), /api/assets/$\{segment}

        # Asset Assignment Service - Assignments
        - id: assetassignment-service-assignments
          uri: lb://assetassignment-service
          predicates:
            - Path=/api/assignments/**
          filters:
            - RewritePath=/api/assignments/(?<segment>.*), /api/assignments/$\{segment}

        # Asset Assignment Service - Requests
        - id: assetassignment-service-requests
          uri: lb://assetassignment-service
          predicates:
            - Path=/api/requests/**
          filters:
            - RewritePath=/api/requests/(?<segment>.*), /api/requests/$\{segment}

        # Audit Reporting Service - Reports
        - id: auditreporting-service-reports
          uri: lb://auditreporting-service
          predicates:
            - Path=/api/reports/**
          filters:
            - RewritePath=/api/reports/(?<segment>.*), /api/reports/$\{segment}

        # Audit Reporting Service - Audit Logs
        - id: auditreporting-service-auditlogs
          uri: lb://auditreporting-service
          predicates:
            - Path=/api/audit/**
          filters:
            - RewritePath=/api/audit/(?<segment>.*), /api/audit/$\{segment}

        # Notification Service
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/notifications/(?<segment>.*), /api/notifications/$\{segment}

  # ✅ Keycloak OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: BHIzMLGMcG3TFSFDOfOFjWU7xa3z70jc
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/ConfigAssets
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ConfigAssets

server:
  port: 8081

# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
