spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:mysql://localhost:3306/notificationdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8086

#eureka configuration for each service independently have to add this below lies there
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
